version: "3"

services:
  db:
    image: mysql:5.7
    container_name: accountbook-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountbook
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mysql/db:/var/lib/mysql