app:
  jwt:
    header: "token"
    issuer: "accountbook"
    tokenSecret: "926D96C90030DD58429D2751AC1BDBBC"
    tokenExpiry: 3600000
    refreshTokenExpiry: 172800000
  domain: "http://localhost:8080"